source 'https://rubygems.org'

gem 'mongoid', github: 'mongoid/mongoid' # Use master branch
gem 'bson_ext' # binary gem


# Private gem
# Generate token here:
# https://github.com/settings/tokens/new
gem 'foobar', git: 'https://OAUTH_TOKEN:x-oauth-basic@github.com/USER/REPONAME.git', branch: 'SOME_BRANCH'

